(function(root){
'use strict';
const W='http://schemas.openxmlformats.org/wordprocessingml/2006/main',R='http://schemas.openxmlformats.org/officeDocument/2006/relationships';
const parse=s=>{const d=new DOMParser().parseFromString(s,'application/xml');if(d.getElementsByTagName('parsererror').length)throw Error('範本 XML 無法解析');return d;};
const xml=d=>new XMLSerializer().serializeToString(d);
const children=(e,n)=>Array.from(e.children).filter(x=>x.namespaceURI===W&&x.localName===n);
const text=e=>Array.from(e.getElementsByTagNameNS(W,'t')).map(x=>x.textContent).join('');
function fill(cell,value){let ps=children(cell,'p');let p=ps[0];if(!p){p=cell.ownerDocument.createElementNS(W,'w:p');cell.appendChild(p);}let r=children(p,'r')[0];let rp=r?.getElementsByTagNameNS(W,'rPr')[0]?.cloneNode(true);for(const c of Array.from(p.children))if(c.localName!=='pPr')p.removeChild(c);ps.slice(1).forEach(x=>x.remove());r=cell.ownerDocument.createElementNS(W,'w:r');if(rp)r.appendChild(rp);String(value??'').split('\n').forEach((line,i)=>{if(i)r.appendChild(cell.ownerDocument.createElementNS(W,'w:br'));let t=cell.ownerDocument.createElementNS(W,'w:t');t.setAttribute('xml:space','preserve');t.textContent=line;r.appendChild(t);});p.appendChild(r);}
const esc=s=>String(s??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
function model(options){const {record,kind,pcr,date,site,stampPosition,vet}=options,a=record.values,C=LabCore;return {id:C.clean(a[1]),owner:C.clean(a[8]),sender:[C.clean(a[7]),C.clean(a[5])||C.clean(a[6])].filter(Boolean).join('／'),vet:C.clean(vet),site:site||C.clean(a[2]),received:C.clean(a[4]),organism:C.clean(a[3]),date,kind,stampPosition:Number(stampPosition),stamp:ASSETS.stamps[C.clean(vet)],pcr:/Escherichia coli/i.test(a[3]||'')?C.pcrText(pcr):'',drugs:C.drugRows(record,kind),row:record.row};}
async function docx(m){
const zip=await JSZip.loadAsync(ASSETS.templates[m.kind],{base64:true});const doc=parse(await zip.file('word/document.xml').async('string'));const body=doc.getElementsByTagNameNS(W,'body')[0],tables=children(body,'tbl'),rows=children(tables[0],'tr');
const slots={'畜主姓名：':m.owner,'送檢人：':m.sender,'收件人：':m.vet,'病例編號：':m.id,'分離部位：':m.site,'送檢日期：':m.received,'細菌鑑定結果：':m.organism,'報告完成日期：':m.date.replaceAll('-','/')};
for(const row of rows){let cells=children(row,'tc');for(let i=0;i<cells.length-1;i++){const key=text(cells[i]).trim();if(Object.hasOwn(slots,key)){fill(cells[i+1],slots[key]);i++;}}}
if(m.kind==='negative'&&rows[3]){if(m.pcr)fill(children(rows[3],'tc').at(-1),m.pcr);else rows[3].remove();}
for(const row of children(tables[1],'tr').slice(1)){if(text(children(row,'tc')[0]).trim()==='Cefquinome')row.remove();}
const drugRows=children(tables[1],'tr').slice(1);if(drugRows.length!==m.drugs.length)throw Error('藥物範本欄位數不一致，已停止產生報告。');drugRows.forEach((row,i)=>{const cells=children(row,'tc');if(text(cells[0]).trim()!==m.drugs[i].name)throw Error('藥物名稱與範本不一致：'+m.drugs[i].name);fill(cells[2],m.drugs[i].value);});
const signCell=children(children(tables[2],'tr')[1],'tc')[m.stampPosition];fill(signCell,m.stamp?'':(m.vet||'獸醫師未指定')+'（待補章）');
if(m.stamp){const s=m.stamp,ext=s.ext==='jpeg'?'jpg':s.ext,relId='rIdAstResponsibleVet',file='ast-responsible-vet.'+ext;zip.file('word/media/'+file,s.data,{base64:true});const rels=parse(await zip.file('word/_rels/document.xml.rels').async('string'));const rel=rels.createElementNS(rels.documentElement.namespaceURI,'Relationship');rel.setAttribute('Id',relId);rel.setAttribute('Type',R+'/image');rel.setAttribute('Target','media/'+file);rels.documentElement.appendChild(rel);zip.file('word/_rels/document.xml.rels',xml(rels));const types=parse(await zip.file('[Content_Types].xml').async('string'));if(!Array.from(types.documentElement.children).some(e=>e.getAttribute('Extension')===ext)){const e=types.createElementNS(types.documentElement.namespaceURI,'Default');e.setAttribute('Extension',ext);e.setAttribute('ContentType',ext==='jpg'?'image/jpeg':'image/png');types.documentElement.appendChild(e);}zip.file('[Content_Types].xml',xml(types));
const cx=1250000,cy=Math.round(cx*s.height/s.width);const drawing=parse(`<w:r xmlns:w="${W}" xmlns:r="${R}" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture"><w:drawing><wp:inline distT="0" distB="0" distL="0" distR="0"><wp:extent cx="${cx}" cy="${cy}"/><wp:docPr id="9101" name="Responsible veterinarian" descr="${esc(m.vet)}"/><a:graphic><a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/picture"><pic:pic><pic:nvPicPr><pic:cNvPr id="9102" name="${file}"/><pic:cNvPicPr/></pic:nvPicPr><pic:blipFill><a:blip r:embed="${relId}"/><a:stretch><a:fillRect/></a:stretch></pic:blipFill><pic:spPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="${cx}" cy="${cy}"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></pic:spPr></pic:pic></a:graphicData></a:graphic></wp:inline></w:drawing></w:r>`);children(signCell,'p')[0].appendChild(doc.importNode(drawing.documentElement,true));}
const issues=m.drugs.filter(d=>d.state==='error'||d.state==='empty');if(issues.length){const p=doc.createElementNS(W,'w:p'),r=doc.createElementNS(W,'w:r'),t=doc.createElementNS(W,'w:t');t.textContent='資料核對：'+issues.map(d=>d.code+' '+(d.state==='error'?'原表資料待確認':'原表未填寫')).join('；')+'。';r.appendChild(t);p.appendChild(r);body.insertBefore(p,tables[2]);}
zip.file('word/document.xml',xml(doc));return zip.generateAsync({type:'blob',mimeType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'});
}
function printHtml(m){const stamp=m.stamp?`<img alt="${esc(m.vet)}印章" style="width:34mm;max-height:16mm;object-fit:contain" src="data:image/${m.stamp.ext==='jpeg'?'jpeg':'png'};base64,${m.stamp.data}">`:esc(m.vet||'獸醫師未指定')+'（待補章）';let signs=['',''];signs[m.stampPosition]=stamp;return `<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><title>${esc(m.id)} 藥物敏感性試驗報告</title><style>@page{size:A4;margin:12mm 15mm}*{box-sizing:border-box}body{font-family:"DFKai-SB","Microsoft JhengHei",serif;color:#000;font-size:11pt;margin:0}h1{text-align:center;font-size:20pt;margin:4mm 0}h2{text-align:center;font-size:16pt;margin:2mm 0 5mm}table{border-collapse:collapse;width:100%;margin-bottom:3mm}td,th{border:1px solid #333;padding:1.3mm 2mm;font-weight:normal}th{text-align:center}p{font-size:9pt;line-height:1.45;margin:2mm 0}tr{break-inside:avoid}.meta th{white-space:nowrap}.sigs td{height:17mm;text-align:center;width:50%}.drug td:last-child{text-align:center;width:24%}.drug td:nth-child(2){text-align:center;width:25%}.screen{background:#eef6f8;padding:10px;font-family:sans-serif;font-size:14px;margin-bottom:15px}@media print{.screen{display:none}}button{padding:8px 16px}</style></head><body><div class="screen">列印版依原範本內容排版；如需保留原 Word 頁首頁尾與版式，請使用 Word 下載。<button onclick="window.print()">列印／另存 PDF</button></div><h1>國立屏東科技大學</h1><h2>動物疾病診斷中心<br>藥物敏感性試驗報告</h2><table class="meta"><tr><th>畜主姓名</th><td>${esc(m.owner)}</td><th>送檢人</th><td>${esc(m.sender)}</td><th>收件人</th><td>${esc(m.vet)}</td></tr><tr><th>病例編號</th><td>${esc(m.id)}</td><th>分離部位</th><td>${esc(m.site)}</td><th>送檢日期</th><td>${esc(m.received)}</td></tr><tr><th>細菌鑑定結果</th><td colspan="3">${esc(m.organism)}</td><th>報告完成日期</th><td>${esc(m.date)}</td></tr>${m.pcr?'<tr><th>毒力基因檢測結果</th><td colspan="5">'+esc(m.pcr)+'</td></tr>':''}</table><table class="drug"><thead><tr><th>藥物名稱</th><th>每試錠藥物含量 (μg)</th><th>藥物敏感性</th></tr></thead><tbody>${m.drugs.map(d=>'<tr><td>'+esc(d.name)+'</td><td>'+esc(d.dose)+'</td><td>'+esc(d.value)+'</td></tr>').join('')}</tbody></table>${ASSETS.notes.map(n=>'<p>'+esc(n)+'</p>').join('')}${m.drugs.some(d=>d.state==='error'||d.state==='empty')?'<p>資料核對：待確認表示原表錯誤或無有效判讀；— 表示原表未填寫。</p>':''}<table class="sigs"><tr><th>檢驗人員簽章</th><th>診斷中心簽章</th></tr><tr><td>${signs[0]}</td><td>${signs[1]}</td></tr></table></body></html>`;}
root.LabReport={model,docx,printHtml};
})(window);
