(function(root){
'use strict';
const W='http://schemas.openxmlformats.org/wordprocessingml/2006/main',R='http://schemas.openxmlformats.org/officeDocument/2006/relationships';
const parse=s=>{const d=new DOMParser().parseFromString(s,'application/xml');if(d.getElementsByTagName('parsererror').length)throw Error('範本 XML 無法解析');return d;};
const xml=d=>new XMLSerializer().serializeToString(d);
const children=(e,n)=>Array.from(e.children).filter(x=>x.namespaceURI===W&&x.localName===n);
const text=e=>Array.from(e.getElementsByTagNameNS(W,'t')).map(x=>x.textContent).join('');
function fill(cell,value){let ps=children(cell,'p');let p=ps[0];if(!p){p=cell.ownerDocument.createElementNS(W,'w:p');cell.appendChild(p);}let r=children(p,'r')[0];let rp=r?.getElementsByTagNameNS(W,'rPr')[0]?.cloneNode(true);for(const c of Array.from(p.children))if(c.localName!=='pPr')p.removeChild(c);ps.slice(1).forEach(x=>x.remove());r=cell.ownerDocument.createElementNS(W,'w:r');if(rp)r.appendChild(rp);String(value??'').split('\n').forEach((line,i)=>{if(i)r.appendChild(cell.ownerDocument.createElementNS(W,'w:br'));let t=cell.ownerDocument.createElementNS(W,'w:t');t.setAttribute('xml:space','preserve');t.textContent=line;r.appendChild(t);});p.appendChild(r);}
const esc=s=>String(s??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
function model(options){const {record,kind,pcr,date,site,vet}=options,a=record.values,C=LabCore,sender=C.clean(a[7]),unit=C.clean(a[5])||C.clean(a[6]),professor='林章豪';return {id:C.clean(a[1]),owner:C.clean(a[8]),sender:sender&&unit?sender+'（'+unit+'）':sender||unit,receiver:C.clean(a[9]),vet:C.clean(vet),professor,site:site||C.clean(a[2]),received:C.clean(a[4]),organism:C.clean(a[3]),date,kind,stamp:ASSETS.stamps[C.clean(vet)],professorStamp:ASSETS.stamps[professor],pcr:/Escherichia coli/i.test(a[3]||'')?C.pcrText(pcr):'',drugs:C.drugRows(record,kind),row:record.row};}
async function docx(m){
const zip=await JSZip.loadAsync(ASSETS.templates[m.kind],{base64:true});const doc=parse(await zip.file('word/document.xml').async('string'));const body=doc.getElementsByTagNameNS(W,'body')[0],tables=children(body,'tbl'),rows=children(tables[0],'tr');
const slots={'畜主姓名：':m.owner,'送檢人：':m.sender,'收件人：':m.receiver,'病例編號：':m.id,'分離部位：':m.site,'送檢日期：':m.received,'細菌鑑定結果：':m.organism,'報告完成日期：':m.date.replaceAll('-','/')};
for(const row of rows){let cells=children(row,'tc');for(let i=0;i<cells.length-1;i++){const key=text(cells[i]).trim();if(Object.hasOwn(slots,key)){fill(cells[i+1],slots[key]);i++;}}}
if(m.kind==='negative'&&rows[3]){if(m.pcr)fill(children(rows[3],'tc').at(-1),m.pcr);else rows[3].remove();}
for(const row of children(tables[1],'tr').slice(1)){if(text(children(row,'tc')[0]).trim()==='Cefquinome')row.remove();}
const drugRows=children(tables[1],'tr').slice(1);if(drugRows.length!==m.drugs.length)throw Error('藥物範本欄位數不一致，已停止產生報告。');drugRows.forEach((row,i)=>{const cells=children(row,'tc');if(text(cells[0]).trim()!==m.drugs[i].name)throw Error('藥物名稱與範本不一致：'+m.drugs[i].name);fill(cells[2],m.drugs[i].value);});
const sigRows=children(tables[2],'tr'),head=children(sigRows[0],'tc'),cells=children(sigRows[1],'tc');fill(head[0],'檢驗人員\n簽章');fill(head[1],'副教授\n簽章');
const rels=parse(await zip.file('word/_rels/document.xml.rels').async('string')),types=parse(await zip.file('[Content_Types].xml').async('string'));
function addStamp(cell,s,name,key,index){fill(cell,s?'':(name||'未指定')+'（待補章）');if(!s)return;const ext=s.ext==='jpeg'?'jpg':s.ext,relId='rIdAst'+key,file='ast-'+key+'.'+ext;zip.file('word/media/'+file,s.data,{base64:true});const rel=rels.createElementNS(rels.documentElement.namespaceURI,'Relationship');rel.setAttribute('Id',relId);rel.setAttribute('Type',R+'/image');rel.setAttribute('Target','media/'+file);rels.documentElement.appendChild(rel);if(!Array.from(types.documentElement.children).some(e=>e.getAttribute('Extension')===ext)){const entry=types.createElementNS(types.documentElement.namespaceURI,'Default');entry.setAttribute('Extension',ext);entry.setAttribute('ContentType',ext==='jpg'?'image/jpeg':'image/png');types.documentElement.appendChild(entry);}const cx=1250000,cy=Math.round(cx*s.height/s.width);const drawing=parse(`<w:r xmlns:w="${W}" xmlns:r="${R}" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture"><w:drawing><wp:inline distT="0" distB="0" distL="0" distR="0"><wp:extent cx="${cx}" cy="${cy}"/><wp:docPr id="${9101+index*2}" name="${key}" descr="${esc(name)}"/><a:graphic><a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/picture"><pic:pic><pic:nvPicPr><pic:cNvPr id="${9102+index*2}" name="${file}"/><pic:cNvPicPr/></pic:nvPicPr><pic:blipFill><a:blip r:embed="${relId}"/><a:stretch><a:fillRect/></a:stretch></pic:blipFill><pic:spPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="${cx}" cy="${cy}"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></pic:spPr></pic:pic></a:graphicData></a:graphic></wp:inline></w:drawing></w:r>`);children(cell,'p')[0].appendChild(doc.importNode(drawing.documentElement,true));}
addStamp(cells[0],m.stamp,m.vet,'ResponsibleVet',0);addStamp(cells[1],m.professorStamp,m.professor,'Professor',1);zip.file('word/_rels/document.xml.rels',xml(rels));zip.file('[Content_Types].xml',xml(types));
const issues=m.drugs.filter(d=>d.state==='error'||d.state==='empty');if(issues.length){const p=doc.createElementNS(W,'w:p'),r=doc.createElementNS(W,'w:r'),t=doc.createElementNS(W,'w:t');t.textContent='資料核對：'+issues.map(d=>d.code+' '+(d.state==='error'?'原表資料待確認':'原表未填寫')).join('；')+'。';r.appendChild(t);p.appendChild(r);body.insertBefore(p,tables[2]);}
zip.file('word/document.xml',xml(doc));return zip.generateAsync({type:'blob',mimeType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'});
}
function printHtml(m){
 const stamp=(s,name)=>s?`<img alt="${esc(name)}印章" src="data:image/${s.ext==='jpeg'?'jpeg':'png'};base64,${s.data}">`:esc(name||'未指定')+'（待補章）';
 const firstNotes=ASSETS.notes.slice(0,2).map(n=>'<p>'+esc(n)+'</p>').join(''),lastNotes=ASSETS.notes.slice(2).map(n=>'<p>'+esc(n)+'</p>').join('');
 const issues=m.drugs.filter(d=>d.state==='error'||d.state==='empty');
 return `<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><title>${esc(m.id)} 藥物敏感性試驗報告</title><style>
@page{size:A4;margin:8mm}*{box-sizing:border-box}body{margin:0;color:#000;font:10pt "DFKai-SB","BiauKai","Microsoft JhengHei",serif}.screen{background:#eef6f8;padding:10px;font:14px sans-serif}.screen button{padding:8px 16px}.page{position:relative;min-height:281mm;border:1px solid #111;padding:5mm 6mm 10mm;overflow:hidden}.page:before{content:"NPUST";position:absolute;top:44%;left:10%;font:88pt Georgia,serif;color:#e5e5e8;transform:rotate(-43deg);z-index:-1}h1,h2{text-align:center;margin:0;font-weight:bold}h1{font-size:17pt;letter-spacing:2mm}h2{font-size:14pt;margin:1mm 0 3mm}.meta{display:grid;grid-template-columns:repeat(3,1fr);gap:1mm 3mm;margin-bottom:4mm}.field{display:flex;align-items:end;white-space:nowrap}.field b{font-weight:normal;margin-right:2mm}.field span{flex:1;text-align:center;border-bottom:1px solid #222;min-height:5mm;overflow:hidden}.field.wide{grid-column:span 2}.field.full{grid-column:1/-1}.drug{border-collapse:collapse;width:100%;border-top:1px solid #111;border-bottom:1px solid #111;margin:2mm 0 1mm}.drug thead{border-bottom:1px solid #111}.drug th,.drug td{border:0;text-align:center;padding:.45mm 1mm;line-height:1.18}.drug th{font-weight:bold}.drug th:first-child,.drug td:first-child{width:48%}.drug th:nth-child(2),.drug td:nth-child(2){width:30%}.drug td:last-child{font-weight:bold}.notes p{font-size:8pt;line-height:1.2;margin:1mm 0}.sigs{border-collapse:collapse;width:100%;margin-top:3mm}.sigs th,.sigs td{border:1px solid #222;width:50%;text-align:center}.sigs th{font-size:10pt;line-height:1.1;height:10mm}.sigs td{height:12mm}.sigs img{width:35mm;max-height:10mm;object-fit:contain}.footer{position:absolute;bottom:2mm;left:0;right:0;text-align:center;font-size:8pt}@media print{.screen{display:none}}
 </style></head><body><div class="screen">請核對報告內容後列印或另存 PDF。 <button onclick="window.print()">列印／另存 PDF</button></div><div class="page"><h1>國立屏東科技大學動物疾病診斷中心</h1><h2>藥物敏感性試驗報告</h2><div class="meta"><div class="field"><b>畜主姓名：</b><span>${esc(m.owner)}</span></div><div class="field"><b>送檢人：</b><span>${esc(m.sender)}</span></div><div class="field"><b>收件人：</b><span>${esc(m.receiver)}</span></div><div class="field"><b>病例編號：</b><span>${esc(m.id)}</span></div><div class="field"><b>分離部位：</b><span>${esc(m.site)}</span></div><div class="field"><b>送檢日期：</b><span>${esc(m.received)}</span></div><div class="field wide"><b>細菌鑑定結果：</b><span><i>${esc(m.organism)}</i></span></div><div class="field"><b>報告完成日期：</b><span>${esc(m.date.replaceAll('-','/'))}</span></div>${m.pcr?'<div class="field full"><b>毒力基因檢測結果：</b><span>'+esc(m.pcr)+'</span></div>':''}</div><table class="drug"><thead><tr><th>藥物名稱</th><th>每試錠藥物含量 (μg)</th><th>藥物敏感性</th></tr></thead><tbody>${m.drugs.map(d=>'<tr><td>'+esc(d.name)+'</td><td>'+esc(d.dose)+'</td><td>'+esc(d.value)+'</td></tr>').join('')}</tbody></table><div class="notes">${firstNotes}${issues.length?'<p>資料核對：'+esc(issues.map(d=>d.code+' '+(d.state==='error'?'原表待確認':'未填寫')).join('；'))+'。</p>':''}</div><table class="sigs"><tr><th>檢驗人員<br>簽章</th><th>副教授<br>簽章</th></tr><tr><td>${stamp(m.stamp,m.vet||'獸醫師未指定')}</td><td>${stamp(m.professorStamp,m.professor)}</td></tr></table><div class="notes">${lastNotes}</div><div class="footer">第 1 頁，共 1 頁</div></div></body></html>`;
}
root.LabReport={model,docx,printHtml};
})(window);
